name: Build Blockstream Green

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        sdk-version: '30.0.3'

    - name: Download and update native libraries
      run: ./gdk/fetch_android_binaries.sh

    - name: Build Android app
      run: ./gradlew build

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: green/build/outputs/apk/production/release/*.apk
